management:
  port: ${MGMT_PORT:8180}

server:
  port: ${SERVER_PORT:8080}

londonair:
  ingest:
    startDate: 2015-01-01
    toDate: 2015-01-02
    bucket:
      raw: ${RAW_BUCKET:AirQualityDataRaw}
      enriched: ${ENRICHED_BUCKET:AirQualityDataEnriched}

# Spring Cloud Stream settings
spring:
  cloud:
    stream:
      bindings:
        output: ${PUBLISH_TOPIC:londonair.ingest.raw}
        output.contentType: application/octet-stream
      binder:
        kafka:
          mode: raw
          zkNodes: ${ZOOKEEPER_NODES:localhost}
          brokers: ${KAFKA_BROKERS:localhost}
